# Generated by Django 3.2.4 on 2021-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/parneetsingh/image/upload/v1/photoshare_image/profile/blank-profile-picture-973460_640_gu5g1r', upload_to='photoshare_image/profile'),
        ),
    ]
