# Generated by Django 3.2.4 on 2021-07-03 07:39

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='photoshare_image/posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='https://res.cloudinary.com/parneetsingh/image/upload/v1/photoshare_image/profile/blank-profile-picture-973460_640_gu5g1r', upload_to='photoshare_image/profile'),
        ),
    ]
