# Generated by Django 3.2.4 on 2021-07-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0009_profile_dissabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dissabled',
            new_name='disabled',
        ),
    ]
