# Generated by Django 3.2.4 on 2021-07-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0010_rename_dissabled_profile_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
