# Generated by Django 3.2.4 on 2021-08-04 12:32

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_profile_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='https://res.cloudinary.com/parneetsingh/image/upload/v1628080124/photoshare_image/profile/blank-profile-picture-973460_1280_szji3x.png', upload_to='photoshare_image/profile'),
        ),
    ]
