# Generated by Django 3.2.4 on 2021-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
