# Generated by Django 3.2.4 on 2021-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
