# Generated by Django 3.2.4 on 2021-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_isdisabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='isDisabled',
        ),
    ]
